### ISSUE TITLE
General comments on codebase

### ISSUE THREAD

**Issue by JosephCrispell** [AlchemistPrimus/data_crunchers_knbs#13]
**Data files**

- Consider loading all input files in single code section and sending into functions as parameters 
- Currently writing data to `iaos_data/` folder that isn't present in repository or `.gitignore` (could risk accidentally uploading). Consider adding data folder and ignoring in `.gitignore` by adding `data/*`

**Coding**

- Consider adding [docstrings](https://pandas.pydata.org/docs/development/contributing_docstring.html#) for functions to give user as much info as possible when using function
- Try and make variable names more verbose and follow a naming convention (python PEP8: https://peps.python.org/pep-0008/)

- Could stored `iaos_data/folium_maps_data/` and add to file names to clean a little. Also, consider using the [`os`](https://www.btelligent.com/en/blog/best-practice-working-with-paths-in-python-part-1/) package to hep with handling paths
- Consider having `clmn`, `col`, `nm`, `lgd_name` as parameters to simplify code:
   https://github.com/AlchemistPrimus/data_crunchers_knbs/blob/a20d34b80ba435b989b91c5487f2e805da56d63d/folium_maps.py#L51-L61

**General**

- Think about 
[variable scope in python](https://www.w3schools.com/python/python_scope.asp)
- In this code could replace with checking if in list of values (`data_frame[data_frame['column_name'].isin(['a', 'b', 'c'])]:
   https://github.com/AlchemistPrimus/data_crunchers_knbs/blob/a20d34b80ba435b989b91c5487f2e805da56d63d/data_cleaning.py#L124-L134

**Comment by equation-man** [comment]
Issues are resolved in mapping.py and datacruchers.py of the application folium_map.py has been broken down to adhere to software syntax

**Comment by TSGreen** [comment]
As mentioned, would be nice to make it explicit in your visualizations that you are showing percentages. 
So change the wording in your legend names from `'Non-Governmental Hospitals Open on Weekends'` to something like `'Non-Governmental Hospitals Open on Weekends (%)'` or `'Percentage of Non-Governmental Hospitals Open on Weekends'` (for example)

**Comment by TSGreen** [comment]
On Joe's point about docstrings. These aren't urgent for the purposes of creating your presentation, but are a good practise to get into when writing code in general. They make it much easier to understand, at a top level, what a function is for and what it does. That way someone reading your code can skim through these and immediately get a good idea of what your overall code is doing and what its for. 

An example of this could be:
```
def core_healthworkforce(Health_staff_2013, Health_staff_2019):
    """
    Calculate relative percentage change of healthcare staff per capita over time.

    Parameters
    ----------
    Health_staff_2013 : pandas.DataFrame
        County wise data of healthcare workforce from 2013
    Health_staff_2019 : pandas.DataFrame
        County wise data of healthcare workforce from 2019

    Returns
    -------
        1) Geojson file generated containing county-wise percentage change in core
           healthcare workforce and county geometry.
        2) CSV file generated containing county-wise percentage change in core
           healthcare workforce.
    """

    # Renaming the columns
    Health_staff_2013.columns = ['counties', 'core_health_workforce_2013']
    Health_staff_2019.columns = ['counties', 'core_health_workforce_2019']
```

As a bonus, when the function is imported into another script (or notebook) the user can get help with understanding the function without having to find where it is written,  by running a `help` command (or just hovering over the function name in some IDEs).

**Comment by Kahacho** [comment]
Thank you, Tim.  We will take that into consideration.

**Comment by TSGreen** [comment]
Hi all, how is progress with the app going? 

I would be really interested in seeing it, so please share a link when that is available 😄

**Comment by Kahacho** [comment]
@AlchemistPrimus  is working on it. We'll definitely share a link.

**Comment by equation-man** [comment]
@TSGreen  and @JosephCrispell doc strings are done they provide full information about the function. Here is the example of our documented mapping function

```
#generating maps
def generate_map(pandas_data,geopandas_shape,column_n,name_,column_lst,cordinates_lst,fields_,aliases_,lgnd_name,fill_clr="RdYIGn"):
    """Returns the map to display the visualization.
    
    parameters
    pandas data and geopandas shape file
    column_n: name of the column to join them with.
    name_:name of the map to generate
    column_lst: column data to include in the map
    cordinates_lst: list of the coordinates(must be two items)
    fields_ and aliases_ are entered as per folium.features.GeojsonTooltip
    lgnd_name: takes the legend name
    fill_clr: takes the color of the fill, can be list but set to RdYIGn by default.
    
    return value
    Html file of the map to be visualized on the webpage by the webapp"""
    if not (isinstance(column_lst,list) and isinstance(coordinates,list) and isinstance(fields_,list) and isinstance(aliases_,list)):
        return "column_lst,fields_,aliases_, cordinates(list that must contain only two items of int or float types), i.e arguments 4th, 5th, 6th and 7th should be lists"
    
    gdf=join_pandas_geopandas(pandas_data,geopandas_shape,column_n)
    coord=polygons(cordinates_lst)
    
    tooltip=folium.features.GeoJsonTooltip(fields=fields_,aliases=aliases_,labels=True,stick=False)
    map_=folium.Map(location=coord,tiles="Stamen Terrain",zoom_start=5)
    cpleth=folium.Choloropleth(gdf,data=gdf,key_on=('features.properties.objectid'),columns=column_lst,fill_color=fill_clr,legend_name=lgnd_name,name=name_)

    cpleth.geojson.add_child(tooltip)
    cpleth.add_to(map_)
    folium.LayerControl().add_to(map_)
    
    map_.save(name_+".html")
```
